name: 'DeployTerraformBack'

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      working-directory: deploy_techtask_only
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working-directory }}

    steps:
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: List all files and directories recursively
      run: |
        echo "Current directory: $(pwd)"
        echo "All files and directories:"
        ls -R
    - name: List all files 
      run: |
        echo "Repository root directory: /home/runner/work/Terraform/Terraform"
        echo "All files and directories in repository root:"
        ls -R /home/runner/work/Terraform/Terraform   

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false
      
    - name: Terraform apply
      run: terraform apply -var="image_tag=f3a0bbdbb3189b4cd9fd030843996293ea5cb95d" -auto-approve -input=false
